### PR TITLE
Revert uw-saml-pyton back to where it was before I tried to fix Azure…

### PR DESCRIPTION
**Pull request by goulter**
…Idp issues.

**Change Description:**  this code released did not work as intended for this fix.

**Closes Github issues**: GH-52

## uw-saml-python Pull Request checklist

- [x] I have run `./scripts/pre-push.sh`
- [x] I have selected a `semver-guidance:` label for this pull request (under labels,
      to the right of the screen)

If you do not do both of these things, your checks will either not run, or have a high probability of failing.

### CODE REVIEW

**Comment by jprosser** [comment]
this would bring us back to 1.2.4 via git revert basically?

**Comment by goulter** [comment]
@jprosser It would have the same effect. The code would be the same as 1.2.4. We get to maintain all the history, rolling forward instead of back.

**Review by jprosser — APPROVED** [review]
All good

**Comment by jprosser** [comment]
> @jprosser It would have the same effect. The code would be the same as 1.2.4. We get to maintain all the history, rolling forward instead of back.

"git revert" is literally a roll forward strategy, just fyi as noted here, https://git-scm.com/docs/git-revert
"git revert is used to record some new commits to reverse the effect of some earlier commits"

**Pull request merged**
